### ISSUE TITLE
Scraper Agent Implementation V1

### ISSUE THREAD

**Issue by nambrot** [abacus-network/abacus-monorepo#885]
Actually implement the scraper agent

- [ ] Create database table schema and table generation code (#969)
- [ ] Create entity code for ORM to work with database (#970)
- [ ] setup provider connections and scrape event data into database (#971)
- [ ] estimate gas to enrich with current message processing status (#972)

Relavent Design artifacts
- https://github.com/abacus-network/abacus-monorepo/issues/414
- https://www.notion.so/Message-Explorer-Scope-62624f0cf2df4e89be8cc9224aa9bf47
